DELETE FROM relatives;
DELETE FROM citizens;
DELETE FROM imports;

DROP TABLE IF EXISTS imports CASCADE ;
DROP TABLE IF EXISTS citizens CASCADE ;
DROP TABLE IF EXISTS relatives CASCADE ;

DROP SEQUENCE IF EXISTS citizens_id_seq;
DROP SEQUENCE IF EXISTS imports_import_id_seq;
